### ISSUE TITLE
有关论文中“trimp”可视化与计算代码

### ISSUE THREAD

**Issue by infinite013** [hanchaoleng/ShapeConv#2]
请问number of misclassified pixels within a narrow band (“trimap”) surrounding ground-truth object boundaries
这一段的错误像素数量计算与范围可视化的代码您能提供一下吗？

**Comment by hanchaoleng** [comment]
您好，在 metrics.py 文件的`class TrimapAccuracy`  可以找到相关代码。

**Comment by infinite013** [comment]
感谢
