### ISSUE TITLE
Thank you very much for your work. I am very interested in your work. I hope you can help explain the meaning of this sentence in the code. The code is in the script 'test_runner. py ' in line 56, as follows:  pred_ rgb[label == 255] = np.array((0, 0, 0))

### ISSUE THREAD

**Issue by 1725917163** [hanchaoleng/ShapeConv#3]
Thank you very much for your work. I am very interested in your work. I hope you can help explain the meaning of this sentence in the code. The code is in the script 'test_runner. py ' in line 56, as follows:

pred_ rgb[label == 255] = np.array((0, 0, 0))

**Comment by hanchaoleng** [comment]
Thank you for your attention, `pred_ rgb[label == 255] = np.array((0, 0, 0))` is used to visualize the unlabeled pixels, note that unlabeled pixels are not involved in the calculation of the final result.

**Comment by 1725917163** [comment]
Thank you very much for taking some time out of your busy schedule to answer my questions
