### ISSUE TITLE
Scales for Test

### ISSUE THREAD

**Issue by Zongwei97** [hanchaoleng/ShapeConv#5]
Hello,

Thanks for the great work ! 

I am confused about the scales in the configs. Why you use multi-scales for testing instead of scale = 1?

For example the code on the configs/nyu/nyu40
    tta=dict(
        scales=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],

Can you provide some explications? Thanks

**Comment by hanchaoleng** [comment]
Multi-scale testing achieve better performance while consuming more computing power.If you want to test on single-scale, you should comment out the tta.We report both single-scale and multi-scale results in our paper and compare them with previous work on the same testing strategy.

**Comment by Zongwei97** [comment]
Thanks for reply !
