### ISSUE TITLE
关于SUN和SID数据集的HHA

### ISSUE THREAD

**Issue by yangjiangeyjg** [hanchaoleng/ShapeConv#7]
作者您好，请问您方便分享SUN和SID数据集的HHA数据连接吗？或者您是怎么将depth转为HHA的呢？需要一些参数吗？
谢谢！

**Comment by hanchaoleng** [comment]
您好，SUN和SID数据集太大，不方便分享，但在repo中有HHA的转换代码。详见：https://github.com/hanchaoleng/ShapeConv/blob/25bee65af4952c10ed4e24f6556765654e56575f/data_preparation/gen_sid.py#L60

**Comment by yangjiangeyjg** [comment]
> 您好，SUN和SID数据集太大，不方便分享，但在repo中有HHA的转换代码。详见：
> 
> https://github.com/hanchaoleng/ShapeConv/blob/25bee65af4952c10ed4e24f6556765654e56575f/data_preparation/gen_sid.py#L60

好的谢谢，请问SID数据集的转换代码有吗？

**Comment by yangjiangeyjg** [comment]
> 您好，SUN和SID数据集太大，不方便分享，但在repo中有HHA的转换代码。详见：
> 
> https://github.com/hanchaoleng/ShapeConv/blob/25bee65af4952c10ed4e24f6556765654e56575f/data_preparation/gen_sid.py#L60

**Comment by yangjiangeyjg** [comment]
> 您好，SUN和SID数据集太大，不方便分享，但在repo中有HHA的转换代码。详见：
> 
> https://github.com/hanchaoleng/ShapeConv/blob/25bee65af4952c10ed4e24f6556765654e56575f/data_preparation/gen_sid.py#L60

谢谢，请问这个转换要花费很多时间吗？您在什么设备上转换了多久呢？

**Comment by hanchaoleng** [comment]
几个小时吧，具体耗时看电脑性能。转换代码有多进程加速，可以充分利用计算资源。

**Comment by yangjiangeyjg** [comment]
> 几个小时吧，具体耗时看电脑性能。转换代码有多进程加速，可以充分利用计算资源。

你好，请问我直接运行代码中的save_hha函数很慢啊，平均处理一张图片要差不多一分钟，几个小时是哪个数据集啊。

**Comment by yangjiangeyjg** [comment]
> 几个小时吧，具体耗时看电脑性能。转换代码有多进程加速，可以充分利用计算资源。

好的谢谢，我明白啦。十分感谢！
